@Invites    = new Meteor.SmartCollection("invites")
@LastInRoom = new Meteor.SmartCollection("last_in_room")
@Messages   = new Meteor.SmartCollection("messages")
@Rooms      = new Meteor.SmartCollection("rooms")
@Rosters    = new Meteor.SmartCollection("rosters")
