@Connections = new Meteor.SmartCollection("connections")
@Invites     = new Meteor.SmartCollection("invites")
@LastInRoom  = new Meteor.SmartCollection("last_in_room")
@Messages    = new Meteor.SmartCollection("messages")
@Rooms       = new Meteor.SmartCollection("rooms")
